name: Build

on: [push, pull_request]

jobs:

  # Actually this whole job requires a full dependencies install!!
  install-pyqt:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    name: "Verify pyqt install"
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install in pyqt5 mode"
        run: "python -m pip install .[pyqt]"
      - name: "Import package"
        run: "python -c 'import fast_scroller; print(fast_scroller.__version__)'"

  install-pyside2:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    name: "Verify pyside2 install"
    runs-on: "${{ matrix.os }}"
    env:
      QT_API: pyside2

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install in pyside2 mode"
        run: "python -m pip install .[pyside2]"
      - name: "Import package"
        run: "python -c 'import fast_scroller; print(fast_scroller.__version__)'"
